#!/bin/bash

declare -r DWM_BINNARY="/usr/local/bin/dwm";
declare -r LOADER=$(readlink -f $0);
declare -r LOADER_NAME="$(basename $LOADER)";
declare -i DO_RELOAD=0;
declare -ri LOOP_TRESHOLD=5;

function logger() {
    /bin/logger -t ${LOADER_NAME} "$@";
}

function hupHandler() {
    DO_RELOAD=$(( $DO_RELOAD + 1));
}

trap hupHandler SIGHUP;

# Black background
xsetroot -solid black
# Fix for Java apps
wmname LG3D

# Launch DBus if needed
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

# Start polkit agent
#/usr/libexec/lxpolkit &

# Start $HOME/.dwm-start if exists
if test -e $HOME/.dwm-start; then
    while read command; do
        binnary="$(echo "$command" | cut -d ' ' -f 1)"
        if [[ -x "$binnary" ]]; then
            eval "$command" || logger "Command '$command' failed to start.";
        else
            logger "Cannot process '$command', binnary '$binnary' doesn't exist or isnt executable."
        fi
    done < $HOME/.dwm-start
fi

while true; do
    if [[ -z "$lastLoop" ]]; then
        lastLoop=$(date +%s);
    else
        if [[ $(( $(date +%s) - $lastLoop )) -le ${LOOP_TRESHOLD} ]]; then
            logger "Reload loop detected quitting."
            break;
        fi
    fi
    logger "Starting DWM session.";
    $DWM_BINNARY;
#    dwmPID=$!;
#    wait $dwmPID;
    rc=$?;
    logger "DWM window manager exited with exit code: $rc";
    if [[ $DO_RELOAD -gt 0 ]]; then
        exec $LOADER;
    fi
    [[ $rc -ne 129 ]] && break;
    logger "Reloading dwm window manager.";
done
